Settings:
  Prefix: '&8[&aCrazyEnchants&8]: '
  InvName: '&4&l&nCrazy Enchanter'
  BookNameColor: '&b&l&n'
  BlackScroll:
    Item: '339'
    Name: '&8&l&nThe Black Scroll'
  T1:
    GUIName: '&c&l&nTier 1'
    GUILore:
      - '&eCost: &6&l20 XP'
    Item: '266'
    XP: 20
    Enchantments:
      - 'Glowing'
      - 'BurnShield'
      - 'Piercing'
      - 'SelfDestruct'
      - 'Springs'
      - 'Gears'
      - 'Hulk'
      - 'Mermaid'
      - 'Ninja'
      - 'Vampire'
      - 'LifeSteal'
      - 'Doctor'
      - 'Boom'
      - 'Venom'
      - 'DoubleDamage'
      - 'SlowMo'
      - 'Blindness'
      - 'Viper'
      - 'AntiGravity'
      - 'FastTurn'
      - 'LightWeight'
      - 'Blessed'
      - 'FeedMe'
      - 'Dizzy'
      - 'Berserk'
      - 'Cursed'
      - 'Rekt'
      - 'Enlightened'
      - 'Freeze'
      - 'Fortify'
      - 'Molten'
      - 'PainGiver'
      - 'Savior'
      - 'Nursery'
  T2:
    GUIName: '&c&l&nTier 2'
    GUILore:
      - '&eCost: &6&l40 XP'
    Item: '264'
    XP: 40
    Enchantments:
      - 'OverLoad'
      - 'Piercing'
      - 'Springs'
      - 'Gears'
      - 'Hulk'
      - 'Ninja'
      - 'Vampire'
      - 'LifeSteal'
      - 'Doctor'
      - 'Boom'
      - 'Venom'
      - 'DoubleDamage'
      - 'SlowMo'
      - 'Blindness'
      - 'Viper'
      - 'AntiGravity'
      - 'FastTurn'
      - 'LightWeight'
      - 'Blessed'
      - 'FeedMe'
      - 'Dizzy'
      - 'Berserk'
      - 'Cursed'
      - 'Rekt'
      - 'Enlightened'
      - 'Freeze'
      - 'Fortify'
      - 'Molten'
      - 'PainGiver'
      - 'Savior'
      - 'Nursery'
  T3:
    GUIName: '&c&l&nTier 3'
    GUILore:
      - '&eCost: &6&l60 XP'
    Item: '388'
    XP: 60
    Enchantments:
      - 'OverLoad'
      - 'Piercing'
      - 'Springs'
      - 'Gears'
      - 'Hulk'
      - 'Ninja'
      - 'Vampire'
      - 'LifeSteal'
      - 'Doctor'
      - 'Boom'
      - 'Venom'
      - 'DoubleDamage'
      - 'SlowMo'
      - 'Blindness'
      - 'Viper'
      - 'AntiGravity'
      - 'FastTurn'
      - 'LightWeight'
      - 'Blessed'
      - 'FeedMe'
      - 'Dizzy'
      - 'Berserk'
      - 'Cursed'
      - 'Rekt'
      - 'Enlightened'
      - 'Freeze'
      - 'Fortify'
      - 'Molten'
      - 'PainGiver'
      - 'Savior'
      - 'Nursery'
  Info:
    GUIName: '&b&l&nInfo'
    Item: '131'