name: CrazyEnchantments
main: me.BadBones69.CrazyEnchantments.Main
version: 1.5.1
softdepend: [Factions, WorldEdit]
description: >
             A Plugin full of Crazy Enchantments.
commands:
  CE:
    description: Opens the Enchanter GUI.
  CrazyEnchantments:
    description: Opens the Enchanter GUI.
  Tinker:
    description: Opens the Tinker GUI.
  Tinkerer:
    description: Opens the Tinker GUI.