name: CrazyEnchantments
author: BadBones69
main: me.BadBones69.CrazyEnchantments.Main
version: 1.7.1.1
softdepend: [Factions, WorldEdit, SilkSpawners, Feudal, ASkyBlock]
website: https://www.spigotmc.org/resources/16470/
description: >
             A Plugin full of Crazy Enchantments.
commands:
  crazyenchantments:
    description: Opens the Enchanter GUI.
    aliases: [ce, enchanter]
  tinkerer:
    description: Opens the Tinker GUI.
    aliases: tinker
  blacksmith:
    description: Opens the Black Smith GUI.
    aliases: [bsmith, blacks, bs]
  gkitz:
    description: Opens the GKitz GUI.
    aliases: [gkit]